apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-jenkins
  labels:
    app: web-jenkins
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: web-jenkins
  template:
    metadata:
      labels:
        app: web-jenkins
    spec:
      containers:
        - name: web-jenkins
          image: gasparottoluo/web-jenkins:latest  # Será sobrescrito pelo Jenkins
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: web-jenkins-service
spec:
  type: NodePort
  selector:
    app: web-jenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
